### PR TITLE
added tests for our header component

### PR DESCRIPTION
**Pull request by JellyBeans1312**

### CODE REVIEW

**Review by KaylaLawson — COMMENTED** [review]
Did the tests pass?

**Comment by JellyBeans1312** [comment]
tests did pass. honestly, i’m not sure about that. i was using the trivia as a reference

**Comment by KaylaLawson** [comment]
> tests did pass. honestly, i’m not sure about that. i was using the trivia as a reference

Yeah I just looked and you're right. I wasn't sure.  I wouldn't be apposed to you working a few more tests.

**Comment by KirbyDD** [comment]
Do we need to commit the snapshot?

**Pull request merged**
